package Exercicios.Banco.BankCreator.BankCreator.Estrutura.Geradores;

import java.util.Random;

public class GeradorDeNome {
    String[] nomes = {

            "Miguel Silva", "Ana Oliveira", "João Pereira", "Sofia Santos", "Pedro Costa",
            "Maria Martins", "Lucas Ferreira", "Beatriz Rodrigues", "Guilherme Lima", "Carolina Almeida",
            "Gabriel Rocha", "Laura Cardoso", "Enzo Carvalho", "Isabela Barbosa", "Matheus Melo",
            "Mariana Souza", "Leonardo Santos", "Valentina Pereira", "Rafael Oliveira", "Clara Lima",
            "Luiz Fernandes", "Giovanna Costa", "Bruno Silva", "Larissa Rocha", "Daniel Alves",
            "Helena Nunes", "Lucas Martins", "Gabriela Mendes", "Thiago Rocha", "Letícia Lima",
            "Lucas Oliveira", "Fernanda Santos", "Gustavo Costa", "Camila Rodrigues", "Nicolas Pereira",
            "Amanda Carvalho", "Matias Cardoso", "Julia Barbosa", "Davi Melo", "Luana Souza",
            "João Santos", "Yasmin Lima", "Rodrigo Fernandes", "Isabela Costa", "Eduardo Rocha",
            "Larissa Almeida", "Cauã Silva", "Sophia Oliveira", "Miguel Lima", "Ana Carolina Rodrigues",
            "André Alves", "Bianca Mendes", "Pedro Carvalho", "Vitória Barbosa", "Gustavo Pereira",
            "Alice Santos", "Lucas Fernandes", "Bruna Costa", "Daniel Rocha", "Clara Oliveira",
            "Gabriel Lima", "Ana Beatriz Martins", "Enzo Oliveira", "Isabella Rodrigues", "Rafael Almeida",
            "Carolina Melo", "Matheus Cardoso", "Julia Mendes", "Miguel Souza", "Lara Carvalho",
            "Thiago Lima", "Mariana Oliveira", "Lucas Fernandes", "Giovanna Costa", "Bruno Silva",
            "Larissa Rocha", "Daniel Alves", "Helena Nunes", "Lucas Martins", "Gabriela Mendes",
            "Thiago Rocha", "Letícia Lima", "Lucas Oliveira", "Fernanda Santos", "Gustavo Costa",
            "Camila Rodrigues", "Nicolas Pereira", "Amanda Carvalho", "Matias Cardoso", "Julia Barbosa",
            "Davi Melo", "Luana Souza", "João Santos", "Yasmin Lima", "Rodrigo Fernandes",
            "Isabela Costa", "Eduardo Rocha", "Larissa Almeida", "Cauã Silva", "Sophia Oliveira",
            "Miguel Lima", "Ana Carolina Rodrigues", "André Alves", "Bianca Mendes", "Pedro Carvalho",
            "Vitória Barbosa", "Gustavo Pereira", "Alice Santos", "Lucas Fernandes", "Bruna Costa",
            "Daniel Rocha", "Clara Oliveira", "Gabriel Lima", "Ana Beatriz Martins", "Enzo Oliveira",
            "Isabella Rodrigues", "Rafael Almeida", "Carolina Melo", "Matheus Cardoso", "Julia Mendes",
            "Miguel Souza", "Lara Carvalho", "Thiago Lima", "Mariana Oliveira", "Lucas Fernandes",
            "Giovanna Costa", "Bruno Silva", "Larissa Rocha", "Daniel Alves", "Helena Nunes",
            "Lucas Martins", "Gabriela Mendes", "Thiago Rocha", "Letícia Lima", "Lucas Oliveira",
            "Fernanda Santos", "Gustavo Costa", "Camila Rodrigues", "Nicolas Pereira", "Amanda Carvalho",
            "Matias Cardoso", "Julia Barbosa", "Davi Melo", "Luana Souza", "João Santos",
            "Yasmin Lima", "Rodrigo Fernandes", "Isabela Costa", "Eduardo Rocha", "Larissa Almeida",
            "Cauã Silva", "Sophia Oliveira", "Miguel Lima", "Ana Carolina Rodrigues", "André Alves",
            "Bianca Mendes", "Pedro Carvalho", "Vitória Barbosa", "Gustavo Pereira", "Alice Santos",
            "Lucas Fernandes", "Bruna Costa", "Daniel Rocha", "Clara Oliveira", "Gabriel Lima",
            "Ana Beatriz Martins", "Enzo Oliveira", "Isabella Rodrigues", "Rafael Almeida", "Carolina Melo",
            "Matheus Cardoso", "Julia Mendes", "Miguel Souza", "Lara Carvalho", "Thiago Lima",
            "Mariana Oliveira", "Lucas Fernandes", "Giovanna Costa", "Bruno Silva", "Larissa Rocha",
            "Daniel Alves", "Helena Nunes", "Lucas Martins", "Gabriela Mendes", "Thiago Rocha",
            "Letícia Lima", "Lucas Oliveira", "Fernanda Santos", "Gustavo Costa", "Camila Rodrigues",
            "Nicolas Pereira", "Amanda Carvalho", "Matias Cardoso", "Julia Barbosa", "Davi Melo",
            "Luana Souza", "João Santos", "Yasmin Lima", "Rodrigo Fernandes", "Isabela Costa",
            "Eduardo Rocha", "Larissa Almeida", "Cauã Silva", "Sophia Oliveira", "Miguel Lima",
            "Ana Carolina Rodrigues", "André Alves", "Bianca Mendes", "Pedro Carvalho", "Vitória Barbosa",
            "Gustavo Pereira", "Alice Santos", "Lucas Fernandes", "Bruna Costa", "Daniel Rocha",
            "Clara Oliveira", "Gabriel Lima", "Ana Beatriz Martins", "Enzo Oliveira", "Isabella Rodrigues",
            "Rafael Almeida", "Carolina Melo", "Matheus Cardoso", "Julia Mendes", "Miguel Souza",
            "Lara Carvalho", "Thiago Lima", "Mariana Oliveira", "Lucas Fernandes", "Giovanna Costa",
            "Bruno Silva", "Larissa Rocha", "Daniel Alves", "Helena Nunes", "Lucas Martins",
            "Gabriela Mendes", "Thiago Rocha", "Letícia Lima", "Lucas Oliveira", "Fernanda Santos",
            "Gustavo Costa", "Camila Rodrigues", "Nicolas Pereira", "Amanda Carvalho", "Matias Cardoso",
            "Julia Barbosa", "Davi Melo", "Luana Souza", "João Santos", "Yasmin Lima",
            "Rodrigo Fernandes", "Isabela Costa", "Eduardo Rocha", "Larissa Almeida", "Cauã Silva",
            "Sophia Oliveira ", "Miguel Lima", "Ana Carolina Rodrigues", "André Alves", "Bianca Mendes",
            "Pedro Carvalho", "Vitória Barbosa", "Gustavo Pereira", "Alice Santos", "Lucas Fernandes",
            "Bruna Costa", "Daniel Rocha", "Clara Oliveira", "Gabriel Lima", "Ana Beatriz Martins",
            "Enzo Oliveira", "Isabella Rodrigues", "Rafael Almeida", "Carolina Melo", "Matheus Cardoso",
            "Julia Mendes", "Miguel Souza", "Lara Carvalho", "Thiago Lima", "Mariana Oliveira",
            "Lucas Fernandes", "Giovanna Costa", "Bruno Silva", "Larissa Rocha", "Daniel Alves",
            "Helena Nunes", "Lucas Martins", "Gabriela Mendes", "Thiago Rocha", "Letícia Lima",
            "Lucas Oliveira", "Fernanda Santos", "Gustavo Costa", "Camila Rodrigues", "Nicolas Pereira",
            "Amanda Carvalho", "Matias Cardoso", "Julia Barbosa", "Davi Melo", "Luana Souza",
            "João Santos", "Yasmin Lima", "Rodrigo Fernandes", "Isabela Costa", "Eduardo Rocha",
            "Larissa Almeida", "Cauã Silva", "Sophia Oliveira", "Miguel Lima", "Ana Carolina Rodrigues",
            "André Alves", "Bianca Mendes", "Pedro Carvalho", "Vitória Barbosa", "Gustavo Pereira",
            "Alice Santos", "Lucas Fernandes", "Bruna Costa", "Daniel Rocha", "Clara Oliveira",
            "Gabriel Lima", "Ana Beatriz Martins", "Enzo Oliveira", "Isabella Rodrigues", "Rafael Almeida",
            "Carolina Melo", "Matheus Cardoso", "Julia Mendes", "Miguel Souza", "Lara Carvalho",
            "Thiago Lima", "Mariana Oliveira", "Lucas Fernandes", "Giovanna Costa", "Bruno Silva",
            "Larissa Rocha", "Daniel Alves", "Helena Nunes", "Lucas Martins", "Gabriela Mendes",
            "Thiago Rocha", "Letícia Lima", "Lucas Oliveira", "Fernanda Santos", "Gustavo Costa",
            "Camila Rodrigues", "Nicolas Pereira", "Amanda Carvalho", "Matias Cardoso", "Julia Barbosa",
            "Davi Melo", "Luana Souza", "João Santos", "Yasmin Lima", "Rodrigo Fernandes",
            "Isabela Costa", "Eduardo Rocha", "Larissa Almeida", "Cauã Silva", "Sophia Oliveira",
            "Miguel Lima", "Ana Carolina Rodrigues", "André Alves", "Bianca Mendes", "Pedro Carvalho",
            "Vitória Barbosa", "Gustavo Pereira", "Alice Santos", "Lucas Fernandes", "Bruna Costa",
            "Daniel Rocha", "Clara Oliveira", "Gabriel Lima", "Ana Beatriz Martins", "Enzo Oliveira",
            "Isabella Rodrigues", "Rafael Almeida", "Carolina Melo", "Matheus Cardoso", "Julia Mendes",
            "Miguel Souza", "Lara Carvalho", "Thiago Lima", "Mariana Oliveira", "Lucas Fernandes",
            "Giovanna Costa", "Bruno Silva", "Larissa Rocha", "Daniel Alves", "Helena Nunes",
            "Lucas Martins", "Gabriela Mendes", "Thiago Rocha", "Letícia Lima", "Lucas Oliveira",
            "Fernanda Santos", "Gustavo Costa", "Camila Rodrigues", "Nicolas Pereira", "Amanda Carvalho",
            "Matias Cardoso", "Julia Barbosa", "Davi Melo", "Luana Souza", "João Santos",
            "Yasmin Lima", "Rodrigo Fernandes", "Isabela Costa", "Eduardo Rocha", "Larissa Almeida",
            "Cauã Silva", "Sophia Oliveira", "Miguel Lima", "Ana Carolina Rodrigues", "André Alves",
            "Bianca Mendes", "Pedro Carvalho", "Vitória Barbosa", "Gustavo Pereira", "Alice Santos",
            "Lucas Fernandes", "Bruna Costa", "Daniel Rocha", "Clara Oliveira", "Gabriel Lima",
            "Ana Beatriz Martins", "Enzo Oliveira", "Isabella Rodrigues", "Rafael Almeida", "Carolina Melo",
            "Matheus Cardoso", "Julia Mendes", "Miguel Souza", "Lara Carvalho", "Thiago Lima",
            "Mariana Oliveira", "Lucas Fernandes", "Giovanna Costa", "Bruno Silva", "Larissa Rocha",
            "Daniel Alves", "Helena Nunes", "Lucas Martins", "Gabriela Mendes", "Thiago Rocha",
            "Letícia Lima", "Lucas Oliveira", "Fernanda Santos", "Gustavo Costa", "Camila Rodrigues",
            "Nicolas Pereira", "Amanda Carvalho", "Matias Cardoso", "Julia Barbosa", "Davi Melo",
            "Luana Souza", "João Santos", "Yasmin Lima", "Rodrigo Fernandes", "Isabela Costa",
            "Eduardo Rocha", "Larissa Almeida", "Cauã Silva", "Sophia Oliveira", "Miguel Lima",
            "Ana Carolina Rodrigues", "André Alves", "Bianca Mendes", "Pedro Carvalho", "Vitória Barbosa",
            "Gustavo Pereira", "Alice Santos", "Lucas Fernandes", "Bruna Costa", "Daniel Rocha",
            "Clara Oliveira", "Gabriel Lima", "Ana Beatriz Martins", "Enzo Oliveira", "Isabella Rodrigues",
            "Rafael Almeida", "Carolina Melo", "Matheus Cardoso", "Julia Mendes", "Miguel Souza",
            "Lara Carvalho", "Thiago Lima", "Mariana Oliveira", "Lucas Fernandes", "Giovanna Costa",
            "Bruno Silva", "Larissa Rocha", "Daniel Alves", "Helena Nunes", "Lucas Martins",
            "Gabriela Mendes", "Thiago Rocha", "Letícia Lima", "Lucas Oliveira", "Fernanda Santos",
            "Gustavo Costa", "Camila Rodrigues", "Nicolas Pereira", "Amanda Carvalho", "Matias Cardoso",
            "Julia Barbosa", "Davi Melo", "Luana Souza", "João Santos", "Yasmin Lima",
            "Rodrigo Fernandes", "Isabela Costa", "Eduardo Rocha", "Larissa Al meida", "Cauã Silva",
            "Sophia Oliveira", "Miguel Lima", "Ana Carolina Rodrigues", "André Alves", "Bianca Mendes",
            "Pedro Carvalho", "Vitória Barbosa", "Gustavo Pereira", "Alice Santos", "Lucas Fernandes",
            "Bruna Costa", "Daniel Rocha", "Clara Oliveira", "Gabriel Lima", "Ana Beatriz Martins",
            "Enzo Oliveira", "Isabella Rodrigues", "Rafael Almeida", "Carolina Melo", "Matheus Cardoso",
            "Julia Mendes", "Miguel Souza", "Lara Carvalho", "Thiago Lima", "Mariana Oliveira"
    };

    public String geraNome() {
        Random random = new Random();
        return nomes[random.nextInt(0,nomes.length)];
    }
}
